# Generated by Django 4.1.6 on 2023-10-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ['-date'], 'verbose_name': 'Email de Remarketing', 'verbose_name_plural': 'Emails para Remarketing'},
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='  '),
        ),
    ]
